### ISSUE TITLE
Error integrating Tailwind CSS Intellisense with Monaco Editor

### ISSUE THREAD

**Issue by Sendhavshab** [remcohaszing/monaco-tailwindcss#88]
**Title:** Error integrating Tailwind CSS Intellisense with Monaco Editor

**Description:**
I have been trying to add Tailwind CSS Intellisense to the Monaco Editor for three weeks but keep encountering an error. Below are the details of the error and the code I am using.

**Error Details:**
```
loader.js:234 Uncaught (in promise)
Error: [object Event]
    at Object.y [as ensureError] (loader.js:234:18)
    at c._createLoadError (loader.js:1461:26)
    at c._onLoadError (loader.js:1472:23)
    at l (loader.js:1615:11)
    at Object.errorback (loader.js:1635:7)
    at y.triggerErrorback (loader.js:601:24)
    at loader.js:588:107
    at HTMLScriptElement.d (loader.js:621:5)
```

**Code:**
```javascript
import { Editor } from '@monaco-editor/react';
import { configureMonacoTailwindcss, tailwindcssData } from 'monaco-tailwindcss';
import { useState } from 'react';

export default function App() {
  const [code, setCode] = useState("");

  window.MonacoEnvironment = {
    getWorker(moduleId, label) {
      switch (label) {
        case 'editorWorkerService':
          return new Worker(new URL('monaco-editor/esm/vs/editor/editor.worker', import.meta.url));
        case 'css':
        case 'less':
        case 'scss':
          return new Worker(new URL('monaco-editor/esm/vs/language/css/css.worker', import.meta.url));
        case 'handlebars':
        case 'html':
        case 'razor':
          return new Worker(new URL('monaco-editor/esm/vs/language/html/html.worker', import.meta.url));
        case 'json':
          return new Worker(new URL('monaco-editor/esm/vs/language/json/json.worker', import.meta.url));
        case 'javascript':
        case 'typescript':
          return new Worker(new URL('monaco-editor/esm/vs/language/typescript/ts.worker', import.meta.url));
        case 'tailwindcss':
          return new Worker(new URL('monaco-tailwindcss/tailwindcss.worker', import.meta.url));
        default:
          throw new Error(`Unknown label ${label}`);
      }
    }
  };

  const mounting = (monaco) => {
    monaco.languages.css.cssDefaults.setOptions({
      data: {
        dataProviders: {
          tailwindcssData
        }
      }
    });

    configureMonacoTailwindcss(monaco);
  };

  return (
    <>
      <Editor
        onMount={mounting}
        onChange={(e, d) => setCode(d)}
        width="100%"
        value={code}
      />
    </>
  );
}
```

**Steps to Reproduce:**
1. Set up a new React project.
2. Install `@monaco-editor/react`, `monaco-tailwindcss`, and their dependencies.
3. Use the provided code to initialize the Monaco Editor with Tailwind CSS Intellisense.
4. Open the browser console to see the error.

**Expected Behavior:**
Tailwind CSS Intellisense should work correctly in the Monaco Editor without any errors.

**Actual Behavior:**
An error "Error: [object Event]" is thrown, preventing Tailwind CSS Intellisense from working.

**Additional Context:**
I have verified that all script paths are correct and accessible. Detailed logging in the `ensureError` function shows that a non-error object is being passed, but I am unable to trace the source of this object.

**Comment by Sendhavshab** [comment]
![image](https://github.com/remcohaszing/monaco-tailwindcss/assets/152778132/84b87aa5-ec9a-4ed7-bda9-2c6719a5b23c)

**Comment by remcohaszing** [comment]
`@monaco-editor/react` loads Monaco from a CDN. I personally recommend against this. I recommend you take time to understand the Monaco editor [concepts](https://github.com/microsoft/monaco-editor#concepts), and integrate the official [`monaco-editor`](https://www.npmjs.com/package/monaco-editor) package in your project directly.

I notice a couple of things:

1. I don’t think it really matters, but you can define `window.MonacoEnvironment` outside of your React component.
   ```js
   import { Editor } from '@monaco-editor/react';
   import { configureMonacoTailwindcss, tailwindcssData } from 'monaco-tailwindcss';
   import { useState } from 'react';
   
   window.MonacoEnvironment = {
     getWorker(moduleId, label) {
       switch (label) {
         case 'editorWorkerService':
           return new Worker(new URL('monaco-editor/esm/vs/editor/editor.worker', import.meta.url));
         case 'css':
         case 'less':
         case 'scss':
           return new Worker(new URL('monaco-editor/esm/vs/language/css/css.worker', import.meta.url));
         case 'handlebars':
         case 'html':
         case 'razor':
           return new Worker(new URL('monaco-editor/esm/vs/language/html/html.worker', import.meta.url));
         case 'json':
           return new Worker(new URL('monaco-editor/esm/vs/language/json/json.worker', import.meta.url));
         case 'javascript':
         case 'typescript':
           return new Worker(new URL('monaco-editor/esm/vs/language/typescript/ts.worker', import.meta.url));
         case 'tailwindcss':
           return new Worker(new URL('monaco-tailwindcss/tailwindcss.worker', import.meta.url));
         default:
           throw new Error(`Unknown label ${label}`);
       }
     }
   };
   
   export default function App() {
     const [code, setCode] = useState("");
   
     const mounting = (monaco) => {
       monaco.languages.css.cssDefaults.setOptions({
         data: {
           dataProviders: {
             tailwindcssData
           }
         }
       });
   
       configureMonacoTailwindcss(monaco);
     };
   
     return (
       <>
         <Editor
           onMount={mounting}
           onChange={(e, d) => setCode(d)}
           width="100%"
           value={code}
         />
       </>
      );
   }
   ```
2. If you do choose to load Monaco from a CDN, you should point the workers there instead of to your local `node_modules`, except for the Tailwind worker:
   ```js
   import { Editor } from '@monaco-editor/react';
   import { configureMonacoTailwindcss, tailwindcssData } from 'monaco-tailwindcss';
   import { useState } from 'react';
   
   window.MonacoEnvironment = {
     getWorker(moduleId, label) {
       switch (label) {
         case 'editorWorkerService':
           return new Worker('https://url-to-your-cdn/monaco-editor/esm/vs/editor/editor.worker.js');
         case 'css':
         case 'less':
         case 'scss':
           return new Worker('https://url-to-your-cdn/monaco-editor/esm/vs/language/css/css.worker.js');
         case 'handlebars':
         case 'html':
         case 'razor':
           return new Worker('https://url-to-your-cdn/monaco-editor/esm/vs/language/html/html.worker.js');
         case 'json':
           return new Worker('https://url-to-your-cdn/monaco-editor/esm/vs/language/json/json.worker.js');
         case 'javascript':
         case 'typescript':
           return new Worker('https://url-to-your-cdn/monaco-editor/esm/vs/language/typescript/ts.worker.js');
         case 'tailwindcss':
           return new Worker(new URL('monaco-tailwindcss/tailwindcss.worker', import.meta.url));
         default:
           throw new Error(`Unknown label ${label}`);
       }
     }
   };
   
   export default function App() {
     const [code, setCode] = useState("");
   
     const mounting = (monaco) => {
       monaco.languages.css.cssDefaults.setOptions({
         data: {
           dataProviders: {
             tailwindcssData
           }
         }
       });
   
       configureMonacoTailwindcss(monaco);
     };
   
     return (
       <>
         <Editor
           onMount={mounting}
           onChange={(e, d) => setCode(d)}
           width="100%"
           value={code}
         />
       </>
      );
   }
   ```
3. You should only configure `monaco-tailwindcss` only once, not every time something changes in React.
   ```js
   import { Editor } from '@monaco-editor/react';
   import { configureMonacoTailwindcss, tailwindcssData } from 'monaco-tailwindcss';
   import { useState } from 'react';
   
   window.MonacoEnvironment = {
     getWorker(moduleId, label) {
       switch (label) {
         case 'editorWorkerService':
           return new Worker('https://url-to-your-cdn/monaco-editor/esm/vs/editor/editor.worker.js');
         case 'css':
         case 'less':
         case 'scss':
           return new Worker('https://url-to-your-cdn/monaco-editor/esm/vs/language/css/css.worker.js');
         case 'handlebars':
         case 'html':
         case 'razor':
           return new Worker('https://url-to-your-cdn/monaco-editor/esm/vs/language/html/html.worker.js');
         case 'json':
           return new Worker('https://url-to-your-cdn/monaco-editor/esm/vs/language/json/json.worker.js');
         case 'javascript':
         case 'typescript':
           return new Worker('https://url-to-your-cdn/monaco-editor/esm/vs/language/typescript/ts.worker.js');
         case 'tailwindcss':
           return new Worker(new URL('monaco-tailwindcss/tailwindcss.worker', import.meta.url));
         default:
           throw new Error(`Unknown label ${label}`);
       }
     }
   };

   let mounted = false;
   function mounting(monaco) {
     if (mounted) {
       return
     }

     monaco.languages.css.cssDefaults.setOptions({
       data: {
         dataProviders: {
           tailwindcssData
         }
       }
     });
   
     configureMonacoTailwindcss(monaco);
   }
   
   export default function App() {
     const [code, setCode] = useState("");
   
     return (
       <>
         <Editor
           onMount={mounting}
           onChange={(e, d) => setCode(d)}
           width="100%"
           value={code}
         />
       </>
      );
   }
   ```

**Comment by remcohaszing** [comment]
You can have a look at the [Vite example](https://github.com/remcohaszing/monaco-tailwindcss/tree/main/examples/vite-example). Typically I recommend explicitly working with models though, not using the `value` option property. 

How you want to hook it into React really depends on your use case.
